### ISSUE TITLE
su password

### ISSUE THREAD

**Issue by fusiondust** [ich777/docker-enigma1-2-bbs#1]
Is there a su password I can use to gain root access and edit config?

**Comment by ich777** [comment]
Docker doesn't work this way.
Please enter on your host machine: 'docker exec -ti --user root [NAME_OF_DOCKER] /bin/bash' to get into the root command lline (without quotes [NAME_OF_DOCKER] stands for your name of the docker eg: 'docker exec -ti --user root ENiGMA1-2 /bin/bash').

Also why can't you edit the files this should be possible, please set the variable UID and GID to the user that needs to edit it.
On wich host did you run this docker?
It was mainly created for Unraid and the readme will be updated in a few days.
